Fixed missing include to readline/history.h
gcc -c -I./src -DSTRNDUP -DSTRNCASECMP -DHAVE_UTYPES -DGNU_READLINE ./src/cmd.c	-o ./obj/cmd.o
./src/cmd.c: In function ‘get_line’:
./src/cmd.c:317:2: warning: implicit declaration of function ‘add_history’ [-Wimplicit-function-declaration]
  add_history (buffer);
  ^~~~~~~~~~~